#!/usr/bin/php
<?php
/**
 * Send messages from the assanka-mail queue to Mailgun
 *
 * @codingstandard ftlabs-phpcs
 * @copyright The Financial Times Limited [All Rights Reserved]
 */

require_once $_SERVER['CORE_PATH'].'/helpers/messaging/beanstalk/v2/beanstalk';

$hosts = array('beanstalk-a:11300', 'beanstalk-b:11300');

foreach ($hosts as $host) {
	$bs = new BeanstalkConnectionV2($host);
	$bs->useTube('assanka-mailgun');
	while ($job = $bs->peekBuried()) {
		echo 'type:job job:'.$job->getID().' host:'.$job->getConn()->getHost().' size:'.strlen($job->getBody());
		$email = json_decode($job->getBody(), true);
		echo ' from:'.$email['from'].' to:'.$email['to'];
		$stats = $job->stats();
		echo ' reserves:'.$stats['reserves'].' age:'.$stats['age']."\n";
		$job->delete();
		unset($job);
	}
}