#!/usr/bin/php
<?php
/**
 * Returns health status information about FT stuff
 *
 * @codingstandard ftlabs-phpcs
 * @copyright The Financial Times Limited [All Rights Reserved]
 */

if (empty($_SERVER['COREFTCO'])) $_SERVER['COREFTCO'] = realpath(dirname(__FILE__).'/../../');

require_once $_SERVER["COREFTCO"]."/processes/global";
if ($_SERVER["DOCUMENT_ROOT"]) exit;

$item = empty($_SERVER["argv"][1]) ? false : $_SERVER["argv"][1];
$var = empty($_SERVER["argv"][2]) ? false : $_SERVER["argv"][2];

switch ($item) {
	case 'sync_to_dam':
	case 'sync_from_dam':
	case 'damupdate_queue_length':

		// Redundant
		echo "0\n";
	break;
	case 'lastdownloadage':
		echo $dbread->querySingle('select UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(max(datelastdamdownload)) from users'), "\n";
	break;
	case 'lastuploadage':
		echo $dbread->querySingle('select UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(max(datelastdamupload)) from users'), "\n";
	break;
	case 'numdownloadedinlastminute':
		echo $dbread->querySingle('select count(*) from users where datelastdamdownload>DATE_SUB(NOW(), INTERVAL 1 MINUTE)'), "\n";
	break;
	case 'markitage':
		echo $dbread->querySingle('select UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(max(date)) from markit_data'), "\n";
	break;
}