#!/usr/local/bin/php
<?php
/**
 * A script which uses the v2 daemon class for use by daemonTest
 *
 * The daemon has a limited execution time and also a callback once the execution has been stopped
 *
 * @codingstandard ftlabs-phpcs
 * @copyright The Financial Times Limited [All rights reserved]
 */
require_once $_SERVER['CORE_PATH'].'/helpers/daemon/v2/daemon';

declare(ticks = 1);
$output = array();
$output['starttime'] = microtime(true);

$daemon = new DaemonV2(array(
	'maxruntime' => 1,
'maxruntimecallback' => function () use ($output) {

		$output['endtime'] = microtime(true);

		file_put_contents(dirname(__FILE__)."/daemonoutput", json_encode($output));
	},
));

sleep(2);

$output['error'] = "maxruntimecallback not called";
file_put_contents(dirname(__FILE__)."/daemonoutput", json_encode($output));