#!/usr/local/bin/php
<?php
/**
 * A daemon which never ends on its own and specifies replaceexisting = true
 *
 * @codingstandard ftlabs-phpcs
 * @copyright The Financial Times Limited [All rights reserved]
 */
require_once $_SERVER['CORE_PATH'].'/helpers/daemon/v2/daemon';


$daemon = new DaemonV2(array(
	'maxinstances' => 3,
	'replaceexisting' => true,
));

while (true) {
	sleep(1);
}